### ISSUE TITLE
helmfile cli namespace param

### ISSUE THREAD

**Issue by tomassatka** [variantdev/chartify#10]
Hi

While using helmfile and setting namespace by cli the namespace after kustomization is set to default.
```
$ helmfile version
helmfile version v0.138.7
```
The code works if namespace is defined in helmfile.yaml under release, BUT if i define such command `helmfile -n namespace-dev template` then the namespace resolved by {{ .Release.Namespace }} is default.

I assume that it has something to do with chartify.go
```		
// Do set namespace if and only if the manifest has no `metadata.namespace` set
		if overrideNamespace == "" && u.Namespace != "" {
			overrideNamespace = u.Namespace
		} 
```

Is that a bug? And if so can I support here to take it up?

Thanks

**Comment by mumoshu** [comment]
> BUT if i define such command helmfile -n namespace-dev template then the namespace resolved by {{ .Release.Namespace }} is default.

Are you talking about helm template here? If so, it looks like the similar bug as https://github.com/roboll/helmfile/issues/1782

**Comment by mumoshu** [comment]
What's the primary goal for you here?

You wanna `hemlfile -n foo template` to produce manifests from your kustomize while all the namespaces are set to `foo`?

**Comment by mumoshu** [comment]
Btw does this relate with chartify?

**Comment by mumoshu** [comment]
@tomassatka Hey! It took literally a year for me to sort this but anyway- I've added a new integration test case to show case how namespace passed to chartify works with kustomize patch, the PR is #28.

Apparently it works as expected (for me) from the perspective of chartify.
So, if there's any issue, it might be caused by Helmfile. Let's track it in helmfile issues!

Thanks again for reporting (and your patience)
